# So Simple Theme - Remote
remote_theme: "mmistakes/so-simple-theme@3.2.0"

# Site Settings
locale: "es-CO"
title: "Arriero Andariego"
description: "Política de Privacidad - Arrierito TV"
baseurl: "/ArrieritoTv-privacy"
url: "https://crhystian27.github.io"
logo: "/ArrieritoTv-privacy/ic_logo.png"

# Site Author
author:
  name: "Arriero Andariego Food Truck"
  picture: "/ArrieritoTv-privacy/ic_logo.png"
  links:
    - title: Instagram
      url: https://www.instagram.com/arrieroandariego1
      icon: fab fa-instagram
    - title: Facebook
      url: https://web.facebook.com/ElArrieroAndariego/
      icon: fab fa-facebook
    - title: WhatsApp
      url: https://wa.me/573238130154
      icon: fab fa-whatsapp
    - title: Ubicación
      url: https://maps.app.goo.gl/tcMBVLJFAHTURiaE7
      icon: fas fa-map-marker-alt

# Skin (default, light, dark)
skin: "default"

# Google Fonts
google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"

# Footer Links
footer_links:
  - title: Instagram
    url: https://www.instagram.com/arrieroandariego1
    icon: fab fa-instagram
  - title: Facebook
    url: https://web.facebook.com/ElArrieroAndariego/
    icon: fab fa-facebook
  - title: WhatsApp
    url: https://wa.me/573238130154
    icon: fab fa-whatsapp
  - title: Ubicación
    url: https://maps.app.goo.gl/tcMBVLJFAHTURiaE7
    icon: fas fa-map-marker-alt

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-remote-theme

# Footer
copyright: "© 2025 Arriero Andariego Food Truck | Since 2015 | Cartago, Colombia"
